import { launchDesktop } from './desktop.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('test-artifacts');fs.mkdirSync(root,{recursive:true});
const data=fs.mkdtempSync(path.join(root,'ui-'));
async function confirmDialog(page, accept=true) { await page.waitForSelector('#confirm-dialog[open]'); await page.click(accept ? '#confirm-accept' : '#confirm-cancel'); }
let app;
try {
  app=await launchDesktop({data});
  const page=app.page;const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.waitForSelector('#welcome-new');await page.screenshot({path:path.join(root,'01-welcome.png')});
  await page.click('#new-chat');await page.fill('#new-cwd',data);await page.fill('#new-model','claude-test-model-id');await page.click('#new-form button[type=submit]');
  await page.waitForFunction(()=>!document.querySelector('#prompt').disabled);
  await app.action('wide'); await page.waitForTimeout(150);
  const widths = await page.evaluate(()=>({messages:document.querySelector('#messages').getBoundingClientRect().width,composer:document.querySelector('.composer').getBoundingClientRect().width}));
  assert.ok(widths.messages>1000,`对话区域宽度应跟随大窗口，实际 ${widths.messages}`);assert.ok(widths.composer>1000,`输入区域宽度应跟随大窗口，实际 ${widths.composer}`);
  const firstId = await page.locator('.session.selected').getAttribute('data-session-id');
  assert.equal(JSON.parse(fs.readFileSync(path.join(data,'sessions',firstId+'.json'))).model,'claude-test-model-id');
  assert.match(await page.locator('.session.selected small').innerText(),/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/);
  const headingLayout=await page.evaluate(()=>{const title=document.querySelector('#title').getBoundingClientRect(),cwd=document.querySelector('#workspace').getBoundingClientRect();return{title,cwd};});
  assert.ok(headingLayout.cwd.left>headingLayout.title.right&&headingLayout.cwd.top<headingLayout.title.bottom&&headingLayout.cwd.bottom>headingLayout.title.top,'标题和工作路径应位于同一行');
  assert.equal(await page.locator('#session-model').count(),1);
  assert.equal(await page.locator('.header-actions').count(),0);
  assert.equal(await page.locator('#status').count(),0);
  await page.fill('#prompt','请帮我分析这个项目');
  await page.locator('#prompt').press('Shift+Enter'); assert.equal(await page.inputValue('#prompt'),'请帮我分析这个项目\n');
  await page.locator('#prompt').dispatchEvent('keydown',{key:'Enter',isComposing:true});
  assert.equal(await page.locator('.message.user').count(),0);
  await page.locator('#prompt').press('Enter');
  await page.waitForSelector('.approval');assert.ok((await page.locator('#messages').innerText()).includes('测试回复'));
  assert.equal(await page.locator('#send').isDisabled(),true);assert.equal(await page.locator('#send').innerText(),'运行中…');
  await page.locator('.session.selected').click({button:'right'});
  assert.equal(await page.locator('#context-delete').isDisabled(),true);
  assert.equal(await page.locator('#context-model').isDisabled(),true);
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>window.hacked),undefined);assert.equal(await page.locator('#messages img').count(),0);
  await page.screenshot({path:path.join(root,'02-permission.png')});
  await app.action('close'); await page.waitForTimeout(200); assert.equal((await app.action('status')).visible,false);
  await app.secondInstance();
  assert.equal((await app.action('status')).visible,true);
  assert.equal(await page.locator('.approval').count(),1);
  await app.action('confirm',false);await app.action('quit');await page.waitForTimeout(250);
  assert.equal(app.child.exitCode,null);assert.equal(await page.locator('.approval').count(),1);
  await app.action('minimize');
  await page.waitForTimeout(200);
  assert.equal((await app.action('status')).visible,false);
  await app.action('show');
  assert.equal((await app.action('status')).visible,true);
  await page.click('.approval .primary');await page.waitForFunction(()=>!document.querySelector('.session.selected')?.classList.contains('busy'));
  assert.equal(await page.locator('#send').innerText(),'发送 ↑');
  assert.ok((await page.locator('#messages').innerText()).includes('已收到允许'));
  await page.fill('#prompt','准备中的草稿');await page.waitForTimeout(500);
  await page.click('#new-chat');await page.fill('#new-cwd',data);assert.equal(await page.inputValue('#new-model'),'');await page.click('#new-form button[type=submit]');
  const secondId = await page.locator('.session').filter({hasText:'新对话'}).getAttribute('data-session-id');
  await page.waitForFunction(id=>document.querySelector('.session.selected')?.dataset.sessionId===id,secondId);
  await page.locator('.session.selected').click({button:'right'});await page.click('#context-rename');await page.fill('#rename-input','待归档对话');await page.click('#rename-form button[type=submit]');
  await page.locator('.session').filter({hasText:'请帮我分析这个项目'}).click();await page.waitForFunction(()=>document.querySelector('#prompt').value==='准备中的草稿');
  await page.click('#settings-button'); assert.equal(await page.inputValue('#send-key'),'enter');
  const settingsLayout=await page.evaluate(()=>{const dialog=document.querySelector('#settings-dialog').getBoundingClientRect(),input=document.querySelector('#cli-path').getBoundingClientRect(),browse=document.querySelector('#pick-cli').getBoundingClientRect(),check=document.querySelector('#check-cli').getBoundingClientRect();return{width:dialog.width,tops:[input.top,browse.top,check.top]};});
  assert.ok(settingsLayout.width>=800,`设置窗口应加宽，实际 ${settingsLayout.width}`);assert.ok(Math.max(...settingsLayout.tops)-Math.min(...settingsLayout.tops)<2,'Claude Code 路径、浏览和检测连接应在同一行');
  assert.equal(await page.locator('.settings-field-help').count(),0);
  await page.screenshot({path:path.join(root,'03-settings-redesign.png')});
  assert.match(await page.locator('#node-info').innerText(),/(应用内置|开发环境) Node v/);
  const projects=path.join(data,'projects');fs.mkdirSync(projects);await page.fill('#default-cwd',projects);
  await page.selectOption('#send-key','shift-enter'); await page.fill('#model','haiku');
  await page.click('#settings-form button[type=submit]'); await page.waitForSelector('#settings-dialog',{state:'hidden'});
  assert.equal(await page.locator('#send-key-hint').innerText(),'Shift + Enter 发送 · Enter 换行');
  const sendLayout=await page.evaluate(()=>{const hint=document.querySelector('#send-key-hint').getBoundingClientRect(),send=document.querySelector('#send').getBoundingClientRect();return{hint,send};});assert.ok(sendLayout.hint.right<sendLayout.send.left&&sendLayout.hint.top<sendLayout.send.bottom&&sendLayout.hint.bottom>sendLayout.send.top,'发送快捷键提示应位于发送按钮左侧');
  await page.locator('#prompt').press('End'); await page.locator('#prompt').press('Enter');
  assert.equal(await page.inputValue('#prompt'),'准备中的草稿\n');
  await page.locator('#prompt').dispatchEvent('keydown',{key:'Enter',shiftKey:true,isComposing:true});
  assert.equal(await page.locator('.message.user').count(),1);
  await page.locator('#prompt').press('Shift+Enter');await page.waitForSelector('.approval');await page.click('#stop');await page.waitForFunction(()=>!document.querySelector('.session.selected')?.classList.contains('busy'));
  assert.equal(await page.locator('.approval').count(),0);
  assert.ok((await page.locator('.session.selected small').innerText()).includes('已停止'));
  await page.locator('.session.selected').click({button:'right'});const modelAction=await page.locator('#context-model').innerText();assert.ok(modelAction.includes('修改模型')&&!modelAction.includes('ID'));assert.equal(await page.locator('#context-open-cwd').isVisible(),true);await page.click('#context-open-cwd');await page.waitForFunction(()=>document.querySelector('#toast').textContent==='已打开当前目录');
  await page.locator('.session.selected').click({button:'right'});assert.equal(await page.locator('#context-export').isVisible(),true);await page.click('#context-model');await page.fill('#session-model','claude-updated-model-id');await page.click('#model-form button[type=submit]');await page.waitForSelector('#model-dialog',{state:'hidden'});
  assert.equal(JSON.parse(fs.readFileSync(path.join(data,'sessions',firstId+'.json'))).model,'claude-updated-model-id');
  await page.locator('.session.selected').click({button:'right'});await page.click('#context-rename');await page.fill('#rename-input','我的项目助手');await page.click('#rename-form button[type=submit]');await page.waitForFunction(()=>document.querySelector('#title').textContent==='我的项目助手');
  await page.screenshot({path:path.join(root,'03-conversation.png')});
  await page.fill('#prompt','删除其他对话时保留草稿');
  // Fixture: debug Rust controls only confirmation responses; menu and storage use the production IPC path.
  await page.locator(`[data-session-id="${secondId}"]`).click({button:'right'}); await page.click('#context-delete');
  await confirmDialog(page,false);
  await page.waitForTimeout(150); assert.equal(await page.locator('.session').count(),2);
  await page.locator(`[data-session-id="${secondId}"]`).click({button:'right'});
  await page.screenshot({path:path.join(root,'04-context-menu.png')}); await page.click('#context-delete');await page.waitForSelector('#confirm-dialog[open]');await page.screenshot({path:path.join(root,'05-archive-confirm.png')});await page.click('#confirm-accept');
  await page.waitForFunction(()=>document.querySelectorAll('.session').length===1);
  assert.equal(await page.locator('.session.selected').getAttribute('data-session-id'),firstId);
  assert.equal(await page.inputValue('#prompt'),'删除其他对话时保留草稿');
  assert.equal(fs.readdirSync(path.join(data,'archive')).some(name=>fs.existsSync(path.join(data,'archive',name,'session.json'))&&JSON.parse(fs.readFileSync(path.join(data,'archive',name,'session.json'))).id===secondId),true);
  await page.click('#settings-button');await page.click('#manage-archive');await page.waitForSelector('.archive-item');
  assert.equal(await page.locator('.archive-item').filter({hasText:'待归档对话'}).count(),1);
  await page.locator('.archive-item').filter({hasText:'待归档对话'}).locator('.archive-restore').click();
  await page.waitForFunction(id=>document.querySelector('.session.selected')?.dataset.sessionId===id,secondId);
  assert.equal(await page.locator('.session').count(),2);
  await page.locator('.session.selected').click({button:'right'});await page.click('#context-delete');await confirmDialog(page,true);
  await page.waitForFunction(()=>document.querySelectorAll('.session').length===1);
  await page.waitForTimeout(500);
  assert.deepEqual(errors,[]);
  await app.close();
  app=await launchDesktop({data});
  const reopened=app.page;await reopened.waitForSelector('.session');
  await reopened.locator('.session').filter({hasText:'我的项目助手'}).click();await reopened.waitForFunction(()=>document.querySelector('#title').textContent==='我的项目助手');assert.ok((await reopened.locator('#messages').innerText()).includes('已收到允许'));
  assert.equal(await reopened.inputValue('#prompt'),'删除其他对话时保留草稿');
  await reopened.click('#settings-button'); assert.equal(await reopened.inputValue('#model'),'haiku');
  await reopened.waitForFunction(()=>document.querySelector('#archive-count').textContent!=='读取中…');
  assert.equal(await reopened.locator('#archive-count').innerText(),'1 个已归档对话');
  await reopened.click('#manage-archive');await reopened.waitForSelector('.archive-item');
  await reopened.screenshot({path:path.join(root,'06-archive.png')});
  await reopened.locator('.archive-item').filter({hasText:'待归档对话'}).locator('.archive-purge').click();await confirmDialog(reopened,false);await reopened.waitForTimeout(100);assert.equal(await reopened.locator('.archive-item').count(),1);
  await reopened.locator('.archive-item').filter({hasText:'待归档对话'}).locator('.archive-purge').click();await confirmDialog(reopened,true);await reopened.waitForFunction(()=>document.querySelectorAll('.archive-item').length===0);
  await reopened.click('#archive-dialog .close-dialog');
  await reopened.waitForSelector('#settings-dialog[open]');await reopened.click('#settings-dialog .close-dialog');
  assert.equal(await reopened.locator('#send-key-hint').innerText(),'Shift + Enter 发送 · Enter 换行');
  await reopened.click('#new-chat');await reopened.waitForSelector('#new-dialog[open]');assert.equal(await reopened.inputValue('#new-cwd'),projects);assert.equal(await reopened.inputValue('#new-model'),'haiku');assert.ok((await reopened.locator('#new-dialog').innerText()).includes('已有项目目录'));await reopened.screenshot({path:path.join(root,'07-new-dialog-work-folder.png')});await reopened.fill('#new-model','claude-opus-test-id');await reopened.click('#new-form button[type=submit]');
  await reopened.waitForFunction(()=>document.querySelector('#title').textContent==='新对话');
  const recycledId = await reopened.locator('.session.selected').getAttribute('data-session-id');
  const recycled=JSON.parse(fs.readFileSync(path.join(data,'sessions',recycledId+'.json')));assert.equal(recycled.model,'claude-opus-test-id');assert.equal(recycled.cwd,projects);assert.equal(fs.statSync(recycled.cwd).isDirectory(),true);assert.equal(fs.existsSync(path.join(projects,'新建对话')),false);
  await reopened.fill('#prompt','随对话进入归档的草稿');
  await reopened.locator('.session.selected').click({button:'right'});await reopened.click('#context-delete');await confirmDialog(reopened,true);
  await reopened.waitForFunction(()=>document.querySelector('#title').textContent==='我的项目助手');
  const recycledDir = fs.readdirSync(path.join(data,'archive')).find(name=>JSON.parse(fs.readFileSync(path.join(data,'archive',name,'session.json'))).id===recycledId);
  assert.equal(JSON.parse(fs.readFileSync(path.join(data,'archive',recycledDir,'session.json'))).draft,'随对话进入归档的草稿');
  await reopened.locator('.session.selected').focus();await reopened.keyboard.press('Shift+F10'); await reopened.click('#context-delete');await confirmDialog(reopened,true);
  await reopened.waitForFunction(()=>document.querySelectorAll('.session').length===0);
  await reopened.waitForFunction(()=>document.querySelector('#prompt').disabled);
  console.log('UI PASS: existing default work folder semantics, exact timestamps, inline title path, running send state, edit model, open directory, context actions, stream, permissions, archives, responsive width and restart persistence (fixture).');
} finally { await app?.close(); }
